version: '3.8'

services:
  snapcast:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        AIRPLAY_VERSION: "1"  # Use AirPlay 1 for simplicity
    container_name: snapcast-dev
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      TZ: "America/New_York"
      
      # AirPlay Configuration (enabled by default)
      AIRPLAY_CONFIG_ENABLED: "1"
      AIRPLAY_DEVICE_NAME: "Snapcast Dev"
      
      # Snapclient Configuration (integrated audio output)
      SNAPCLIENT_ENABLED: "1"
      SNAPCLIENT_HOST: "localhost"
      SNAPCLIENT_SOUNDCARD: "plughw:1,0"  # RPi 4 headphone jack
      SNAPCLIENT_LATENCY: "0"
      
      # HTTPS (disabled for dev to simplify)
      HTTPS_ENABLED: "0"
      
      # Disable unnecessary features
      SPOTIFY_CONFIG_ENABLED: "0"
      PIPE_CONFIG_ENABLED: "0"
      META_CONFIG_ENABLED: "0"
    volumes:
      - snapcast-data:/app/data/
      - snapcast-config:/app/config/
      - /tmp:/tmp
    devices:
      - /dev/snd:/dev/snd

volumes:
  snapcast-data:
  snapcast-config: