version: '3.8'

services:
  snapcast:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: snapcast-dev
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      TZ: "America/New_York"

      # AirPlay Configuration
      AIRPLAY_CONFIG_ENABLED: "1"
      AIRPLAY_DEVICE_NAME: "Snapcast Dev"

      # Snapclient for local audio output
      SNAPCLIENT_ENABLED: "1"
      SNAPCLIENT_HOST: "localhost"
      SNAPCLIENT_SOUNDCARD: "plughw:1,0"
      SNAPCLIENT_LATENCY: "0"

      # Optional: Spotify (disabled by default)
      SPOTIFY_CONFIG_ENABLED: "0"

      # Optional: HTTPS (disabled for dev)
      HTTPS_ENABLED: "0"
    volumes:
      - snapcast-data:/app/data/
      - snapcast-config:/app/config/
    devices:
      - /dev/snd:/dev/snd

volumes:
  snapcast-data:
  snapcast-config: