services:
  snapserver:
    image: ${DOCKER_USERNAME}/plum-snapcast-server:${TAG:-latest}
    container_name: plum-snapcast-server
    restart: always
    network_mode: host
    environment:
      TZ: "${TZ:-UTC}"
      AIRPLAY_CONFIG_ENABLED: "${AIRPLAY_CONFIG_ENABLED:-1}"
      AIRPLAY_SOURCE_NAME: "${AIRPLAY_SOURCE_NAME:-Airplay}"
      AIRPLAY_DEVICE_NAME: "${AIRPLAY_DEVICE_NAME:-Snapcast}"
      AIRPLAY_PORT: "${AIRPLAY_PORT:-5000}"
      SPOTIFY_CONFIG_ENABLED: "${SPOTIFY_CONFIG_ENABLED:-0}"
      SPOTIFY_SOURCE_NAME: "${SPOTIFY_SOURCE_NAME:-Spotify}"
      SPOTIFY_DEVICE_NAME: "${SPOTIFY_DEVICE_NAME:-Snapcast}"
      SPOTIFY_BITRATE: "${SPOTIFY_BITRATE:-320}"
      PIPE_CONFIG_ENABLED: "${PIPE_CONFIG_ENABLED:-0}"
      HTTPS_ENABLED: "${HTTPS_ENABLED:-1}"
    volumes:
      - snapcast-data:/app/data/
      - snapcast-config:/app/config/
      - snapcast-certs:/app/certs/
      - /tmp:/tmp  # Share /tmp for pipes
    devices:
      - /dev/snd:/dev/snd  # Audio device access
    cap_add:
      - SYS_NICE  # For audio priority

  frontend:
    image: ${DOCKER_USERNAME}/plum-snapcast-frontend:${TAG:-latest}
    container_name: plum-snapcast-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - snapserver

volumes:
  snapcast-data:
    driver: local
  snapcast-config:
    driver: local  
  snapcast-certs:
    driver: local
